### ISSUE TITLE
Function Addr and Offset

### ISSUE THREAD

**Issue by sraboy** [kenoph/nampa#3]
I don't use Binja so I'm not sure how it's handled there but the callback returns the plain `addr`. The `addr` only refers to the buffer so the matched function's actual address in the binary is at `addr+funk.offset`.

Was that intentional?

**Comment by thebabush** [comment]
`addr` is actually the offset inside the buffer given to the matching function, yes. In the case of the Binja plugin I wrote, buffers start at the beginning of functions so `addr + funk.offset` is correct. It made sense in my head :)

The naming of the variable isn't great... But other than that, is there something I'm missing? My idea was that a "dumb" matching function is actually better since it can be easily adapted to any situation. I'm open to suggestions ;)

**Comment by sraboy** [comment]
Haha, I think it's just the naming throwing me off. I'm with you on the "dumb" function thing (though a **kwargs could be helpful). 

I'm working on implementing ref funcs and, with angr, I also have to consider its `symbol.relative_addr` and `kb.function.addr`, plus the binary's remapped base address. Coupled with `addr+funk.offset`, there's just a lot of `addr` vars being thrown around.

**Comment by thebabush** [comment]
Feel free to rename / change things however you want ;) as long as it is still easy to use and works as intended.

**Comment by sraboy** [comment]
No problem. I mostly wanted to be sure I was understanding it correctly. If I end up doing a more substantive PR for REF functions, I might throw that in as a commit but I try not to change "internal implementation" details.
